// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderNo.proto

package proto_datasvr

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OrderType int32

const (
	OrderType_ORDER_TYPE_NONE       OrderType = 0
	OrderType_ORDER_TYPE_BB_ENTRUST OrderType = 1
	OrderType_ORDER_TYPE_BB_TRADE   OrderType = 2
	OrderType_ORDER_TYPE_OTC_AD     OrderType = 3
	OrderType_ORDER_TYPE_OTC_TRADE  OrderType = 4
)

var OrderType_name = map[int32]string{
	0: "ORDER_TYPE_NONE",
	1: "ORDER_TYPE_BB_ENTRUST",
	2: "ORDER_TYPE_BB_TRADE",
	3: "ORDER_TYPE_OTC_AD",
	4: "ORDER_TYPE_OTC_TRADE",
}

var OrderType_value = map[string]int32{
	"ORDER_TYPE_NONE":       0,
	"ORDER_TYPE_BB_ENTRUST": 1,
	"ORDER_TYPE_BB_TRADE":   2,
	"ORDER_TYPE_OTC_AD":     3,
	"ORDER_TYPE_OTC_TRADE":  4,
}

func (x OrderType) String() string {
	return proto.EnumName(OrderType_name, int32(x))
}

func (OrderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c11a259be2d7b15d, []int{0}
}

// 生成订单序号
type GenOrderNoRequest struct {
	OrderType            OrderType `protobuf:"varint,1,opt,name=order_type,json=orderType,proto3,enum=proto.datasvr.OrderType" json:"order_type,omitempty"`
	Step                 int32     `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GenOrderNoRequest) Reset()         { *m = GenOrderNoRequest{} }
func (m *GenOrderNoRequest) String() string { return proto.CompactTextString(m) }
func (*GenOrderNoRequest) ProtoMessage()    {}
func (*GenOrderNoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c11a259be2d7b15d, []int{0}
}

func (m *GenOrderNoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenOrderNoRequest.Unmarshal(m, b)
}
func (m *GenOrderNoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenOrderNoRequest.Marshal(b, m, deterministic)
}
func (m *GenOrderNoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenOrderNoRequest.Merge(m, src)
}
func (m *GenOrderNoRequest) XXX_Size() int {
	return xxx_messageInfo_GenOrderNoRequest.Size(m)
}
func (m *GenOrderNoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenOrderNoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenOrderNoRequest proto.InternalMessageInfo

func (m *GenOrderNoRequest) GetOrderType() OrderType {
	if m != nil {
		return m.OrderType
	}
	return OrderType_ORDER_TYPE_NONE
}

func (m *GenOrderNoRequest) GetStep() int32 {
	if m != nil {
		return m.Step
	}
	return 0
}

type GenOrderNoResponse struct {
	Code                 int32                    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string                   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *GenOrderNoResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GenOrderNoResponse) Reset()         { *m = GenOrderNoResponse{} }
func (m *GenOrderNoResponse) String() string { return proto.CompactTextString(m) }
func (*GenOrderNoResponse) ProtoMessage()    {}
func (*GenOrderNoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c11a259be2d7b15d, []int{1}
}

func (m *GenOrderNoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenOrderNoResponse.Unmarshal(m, b)
}
func (m *GenOrderNoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenOrderNoResponse.Marshal(b, m, deterministic)
}
func (m *GenOrderNoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenOrderNoResponse.Merge(m, src)
}
func (m *GenOrderNoResponse) XXX_Size() int {
	return xxx_messageInfo_GenOrderNoResponse.Size(m)
}
func (m *GenOrderNoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenOrderNoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenOrderNoResponse proto.InternalMessageInfo

func (m *GenOrderNoResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GenOrderNoResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GenOrderNoResponse) GetData() *GenOrderNoResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type GenOrderNoResponse_Data struct {
	OrderSymbol          string   `protobuf:"bytes,1,opt,name=order_symbol,json=orderSymbol,proto3" json:"order_symbol,omitempty"`
	NoStart              int64    `protobuf:"varint,2,opt,name=no_start,json=noStart,proto3" json:"no_start,omitempty"`
	NoEnd                int64    `protobuf:"varint,3,opt,name=no_end,json=noEnd,proto3" json:"no_end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenOrderNoResponse_Data) Reset()         { *m = GenOrderNoResponse_Data{} }
func (m *GenOrderNoResponse_Data) String() string { return proto.CompactTextString(m) }
func (*GenOrderNoResponse_Data) ProtoMessage()    {}
func (*GenOrderNoResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_c11a259be2d7b15d, []int{1, 0}
}

func (m *GenOrderNoResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenOrderNoResponse_Data.Unmarshal(m, b)
}
func (m *GenOrderNoResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenOrderNoResponse_Data.Marshal(b, m, deterministic)
}
func (m *GenOrderNoResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenOrderNoResponse_Data.Merge(m, src)
}
func (m *GenOrderNoResponse_Data) XXX_Size() int {
	return xxx_messageInfo_GenOrderNoResponse_Data.Size(m)
}
func (m *GenOrderNoResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GenOrderNoResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GenOrderNoResponse_Data proto.InternalMessageInfo

func (m *GenOrderNoResponse_Data) GetOrderSymbol() string {
	if m != nil {
		return m.OrderSymbol
	}
	return ""
}

func (m *GenOrderNoResponse_Data) GetNoStart() int64 {
	if m != nil {
		return m.NoStart
	}
	return 0
}

func (m *GenOrderNoResponse_Data) GetNoEnd() int64 {
	if m != nil {
		return m.NoEnd
	}
	return 0
}

func init() {
	proto.RegisterEnum("proto.datasvr.OrderType", OrderType_name, OrderType_value)
	proto.RegisterType((*GenOrderNoRequest)(nil), "proto.datasvr.GenOrderNoRequest")
	proto.RegisterType((*GenOrderNoResponse)(nil), "proto.datasvr.GenOrderNoResponse")
	proto.RegisterType((*GenOrderNoResponse_Data)(nil), "proto.datasvr.GenOrderNoResponse.Data")
}

func init() { proto.RegisterFile("orderNo.proto", fileDescriptor_c11a259be2d7b15d) }

var fileDescriptor_c11a259be2d7b15d = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0xc5, 0xd8, 0x40, 0x3d, 0x94, 0xd6, 0x0c, 0x45, 0x35, 0x9c, 0x0c, 0x87, 0x0a, 0xf5, 0xe0,
	0x03, 0x3d, 0x54, 0xea, 0x0d, 0x6a, 0x8b, 0x4b, 0x64, 0x47, 0x8b, 0xa3, 0x28, 0xca, 0xc1, 0x31,
	0xf1, 0x2a, 0x97, 0xb0, 0xeb, 0x78, 0x37, 0x91, 0xf8, 0x80, 0x7c, 0x61, 0x7e, 0x28, 0xf2, 0x38,
	0x89, 0x80, 0x48, 0xc9, 0xc9, 0x6f, 0xde, 0xcc, 0x9b, 0x37, 0x7e, 0x0b, 0x3d, 0x59, 0xe6, 0xbc,
	0x8c, 0xa4, 0x5f, 0x94, 0x52, 0x4b, 0xec, 0xd1, 0xc7, 0xcf, 0x33, 0x9d, 0xa9, 0x87, 0x72, 0x7a,
	0x05, 0xfd, 0x15, 0x17, 0x71, 0x3d, 0xc2, 0xf8, 0xdd, 0x3d, 0x57, 0x1a, 0xff, 0x02, 0x90, 0x28,
	0xd5, 0xbb, 0x82, 0xbb, 0x86, 0x67, 0xcc, 0xbe, 0xcd, 0x5d, 0xff, 0x40, 0xe8, 0x93, 0x24, 0xd9,
	0x15, 0x9c, 0xd9, 0xf2, 0x15, 0x22, 0x82, 0xa5, 0x34, 0x2f, 0xdc, 0xa6, 0x67, 0xcc, 0x5a, 0x8c,
	0xf0, 0xf4, 0xc9, 0x00, 0xdc, 0xb7, 0x50, 0x85, 0x14, 0x8a, 0x46, 0xaf, 0x65, 0x5e, 0x6f, 0x6f,
	0x31, 0xc2, 0xe8, 0x80, 0xb9, 0x55, 0x37, 0xa4, 0xb6, 0x59, 0x05, 0xf1, 0x1f, 0x58, 0x95, 0xa1,
	0x6b, 0x7a, 0xc6, 0xac, 0x3b, 0xff, 0x75, 0x74, 0xc3, 0xfb, 0xb5, 0x7e, 0x90, 0xe9, 0x8c, 0x91,
	0x66, 0x7c, 0x09, 0x56, 0x55, 0xe1, 0x04, 0xbe, 0xd6, 0x7f, 0xa3, 0x76, 0xdb, 0x8d, 0xbc, 0x25,
	0x47, 0x9b, 0x75, 0x89, 0x5b, 0x13, 0x85, 0x23, 0xf8, 0x22, 0x64, 0xaa, 0x74, 0x56, 0x6a, 0x72,
	0x37, 0x59, 0x47, 0xc8, 0x75, 0x55, 0xe2, 0x10, 0xda, 0x42, 0xa6, 0x5c, 0xe4, 0x74, 0x83, 0xc9,
	0x5a, 0x42, 0x86, 0x22, 0xff, 0xfd, 0x68, 0x80, 0xfd, 0x16, 0x01, 0x0e, 0xe0, 0x7b, 0xcc, 0x82,
	0x90, 0xa5, 0xc9, 0xc5, 0x69, 0x98, 0x46, 0x71, 0x14, 0x3a, 0x0d, 0x1c, 0xc1, 0x70, 0x8f, 0x5c,
	0x2e, 0xd3, 0x30, 0x4a, 0xd8, 0xd9, 0x3a, 0x71, 0x0c, 0xfc, 0x09, 0x83, 0xc3, 0x56, 0xc2, 0x16,
	0x41, 0xe8, 0x34, 0x71, 0x08, 0xfd, 0xbd, 0x46, 0x9c, 0xfc, 0x4f, 0x17, 0x81, 0x63, 0xa2, 0x0b,
	0x3f, 0x8e, 0xe8, 0x5a, 0x60, 0xcd, 0xcf, 0xa1, 0xf3, 0x12, 0x01, 0x9e, 0x80, 0xb9, 0xe2, 0x02,
	0xbd, 0x0f, 0x42, 0xa2, 0xe7, 0x1d, 0x4f, 0x3e, 0x8d, 0x71, 0xda, 0xd8, 0xb4, 0x69, 0xe6, 0xcf,
	0x73, 0x00, 0x00, 0x00, 0xff, 0xff, 0x62, 0x26, 0x6d, 0xa7, 0x3f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderNoClient is the client API for OrderNo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderNoClient interface {
	// 生成订单序号
	Gen(ctx context.Context, in *GenOrderNoRequest, opts ...grpc.CallOption) (*GenOrderNoResponse, error)
}

type orderNoClient struct {
	cc *grpc.ClientConn
}

func NewOrderNoClient(cc *grpc.ClientConn) OrderNoClient {
	return &orderNoClient{cc}
}

func (c *orderNoClient) Gen(ctx context.Context, in *GenOrderNoRequest, opts ...grpc.CallOption) (*GenOrderNoResponse, error) {
	out := new(GenOrderNoResponse)
	err := c.cc.Invoke(ctx, "/proto.datasvr.OrderNo/Gen", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderNoServer is the server API for OrderNo service.
type OrderNoServer interface {
	// 生成订单序号
	Gen(context.Context, *GenOrderNoRequest) (*GenOrderNoResponse, error)
}

func RegisterOrderNoServer(s *grpc.Server, srv OrderNoServer) {
	s.RegisterService(&_OrderNo_serviceDesc, srv)
}

func _OrderNo_Gen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenOrderNoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderNoServer).Gen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.datasvr.OrderNo/Gen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderNoServer).Gen(ctx, req.(*GenOrderNoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderNo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.datasvr.OrderNo",
	HandlerType: (*OrderNoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Gen",
			Handler:    _OrderNo_Gen_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orderNo.proto",
}
