// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserListRequest struct {
	IsPage    bool  `protobuf:"varint,1,opt,name=is_page,json=isPage,proto3" json:"is_page,omitempty"`
	PageIndex int32 `protobuf:"varint,2,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageSize  int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Types that are valid to be assigned to FilterName:
	//	*UserListRequest_Name
	FilterName           isUserListRequest_FilterName `protobuf_oneof:"filter_name"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *UserListRequest) Reset()         { *m = UserListRequest{} }
func (m *UserListRequest) String() string { return proto.CompactTextString(m) }
func (*UserListRequest) ProtoMessage()    {}
func (*UserListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListRequest.Unmarshal(m, b)
}
func (m *UserListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListRequest.Marshal(b, m, deterministic)
}
func (m *UserListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListRequest.Merge(m, src)
}
func (m *UserListRequest) XXX_Size() int {
	return xxx_messageInfo_UserListRequest.Size(m)
}
func (m *UserListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserListRequest proto.InternalMessageInfo

func (m *UserListRequest) GetIsPage() bool {
	if m != nil {
		return m.IsPage
	}
	return false
}

func (m *UserListRequest) GetPageIndex() int32 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *UserListRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type isUserListRequest_FilterName interface {
	isUserListRequest_FilterName()
}

type UserListRequest_Name struct {
	Name string `protobuf:"bytes,4,opt,name=name,proto3,oneof"`
}

func (*UserListRequest_Name) isUserListRequest_FilterName() {}

func (m *UserListRequest) GetFilterName() isUserListRequest_FilterName {
	if m != nil {
		return m.FilterName
	}
	return nil
}

func (m *UserListRequest) GetName() string {
	if x, ok := m.GetFilterName().(*UserListRequest_Name); ok {
		return x.Name
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UserListRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UserListRequest_OneofMarshaler, _UserListRequest_OneofUnmarshaler, _UserListRequest_OneofSizer, []interface{}{
		(*UserListRequest_Name)(nil),
	}
}

func _UserListRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UserListRequest)
	// filter_name
	switch x := m.FilterName.(type) {
	case *UserListRequest_Name:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Name)
	case nil:
	default:
		return fmt.Errorf("UserListRequest.FilterName has unexpected type %T", x)
	}
	return nil
}

func _UserListRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UserListRequest)
	switch tag {
	case 4: // filter_name.name
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.FilterName = &UserListRequest_Name{x}
		return true, err
	default:
		return false, nil
	}
}

func _UserListRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UserListRequest)
	// filter_name
	switch x := m.FilterName.(type) {
	case *UserListRequest_Name:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Name)))
		n += len(x.Name)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type UserListResponse struct {
	Code                 int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *UserListResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UserListResponse) Reset()         { *m = UserListResponse{} }
func (m *UserListResponse) String() string { return proto.CompactTextString(m) }
func (*UserListResponse) ProtoMessage()    {}
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResponse.Unmarshal(m, b)
}
func (m *UserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResponse.Marshal(b, m, deterministic)
}
func (m *UserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResponse.Merge(m, src)
}
func (m *UserListResponse) XXX_Size() int {
	return xxx_messageInfo_UserListResponse.Size(m)
}
func (m *UserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResponse proto.InternalMessageInfo

func (m *UserListResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserListResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *UserListResponse) GetData() *UserListResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserListResponse_Data struct {
	IsPage               bool                          `protobuf:"varint,1,opt,name=is_page,json=isPage,proto3" json:"is_page,omitempty"`
	PageIndex            int32                         `protobuf:"varint,2,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageSize             int32                         `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageCount            int32                         `protobuf:"varint,4,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	Total                int32                         `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	Items                []*UserListResponse_Data_Item `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *UserListResponse_Data) Reset()         { *m = UserListResponse_Data{} }
func (m *UserListResponse_Data) String() string { return proto.CompactTextString(m) }
func (*UserListResponse_Data) ProtoMessage()    {}
func (*UserListResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1, 0}
}

func (m *UserListResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResponse_Data.Unmarshal(m, b)
}
func (m *UserListResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResponse_Data.Marshal(b, m, deterministic)
}
func (m *UserListResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResponse_Data.Merge(m, src)
}
func (m *UserListResponse_Data) XXX_Size() int {
	return xxx_messageInfo_UserListResponse_Data.Size(m)
}
func (m *UserListResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResponse_Data proto.InternalMessageInfo

func (m *UserListResponse_Data) GetIsPage() bool {
	if m != nil {
		return m.IsPage
	}
	return false
}

func (m *UserListResponse_Data) GetPageIndex() int32 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *UserListResponse_Data) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *UserListResponse_Data) GetPageCount() int32 {
	if m != nil {
		return m.PageCount
	}
	return 0
}

func (m *UserListResponse_Data) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *UserListResponse_Data) GetItems() []*UserListResponse_Data_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type UserListResponse_Data_Item struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListResponse_Data_Item) Reset()         { *m = UserListResponse_Data_Item{} }
func (m *UserListResponse_Data_Item) String() string { return proto.CompactTextString(m) }
func (*UserListResponse_Data_Item) ProtoMessage()    {}
func (*UserListResponse_Data_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1, 0, 0}
}

func (m *UserListResponse_Data_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResponse_Data_Item.Unmarshal(m, b)
}
func (m *UserListResponse_Data_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResponse_Data_Item.Marshal(b, m, deterministic)
}
func (m *UserListResponse_Data_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResponse_Data_Item.Merge(m, src)
}
func (m *UserListResponse_Data_Item) XXX_Size() int {
	return xxx_messageInfo_UserListResponse_Data_Item.Size(m)
}
func (m *UserListResponse_Data_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResponse_Data_Item.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResponse_Data_Item proto.InternalMessageInfo

func (m *UserListResponse_Data_Item) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserListResponse_Data_Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserListResponse_Data_Item) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*UserListRequest)(nil), "proto.UserListRequest")
	proto.RegisterType((*UserListResponse)(nil), "proto.UserListResponse")
	proto.RegisterType((*UserListResponse_Data)(nil), "proto.UserListResponse.Data")
	proto.RegisterType((*UserListResponse_Data_Item)(nil), "proto.UserListResponse.Data.Item")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x6d, 0xda, 0x4d, 0x6d, 0xa6, 0x88, 0x65, 0x29, 0x36, 0x54, 0x85, 0xd8, 0x53, 0x4e, 0x41,
	0xea, 0x41, 0xbc, 0x08, 0x7e, 0x1c, 0x2c, 0x78, 0x90, 0x15, 0xcf, 0x61, 0x6d, 0xc6, 0xb2, 0xd0,
	0x7c, 0x98, 0xdd, 0x80, 0xf4, 0x1f, 0x88, 0xff, 0xd7, 0xb3, 0xcc, 0x44, 0x11, 0x14, 0xbd, 0x79,
	0xca, 0x7b, 0x6f, 0x66, 0x32, 0xef, 0x0d, 0x0b, 0xd0, 0x58, 0xac, 0x93, 0xaa, 0x2e, 0x5d, 0x29,
	0x7d, 0xfe, 0xcc, 0x5e, 0x3d, 0xd8, 0xb9, 0xb7, 0x58, 0xdf, 0x18, 0xeb, 0x14, 0x3e, 0x35, 0x68,
	0x9d, 0x9c, 0xc0, 0x96, 0xb1, 0x69, 0xa5, 0x57, 0x18, 0x7a, 0x91, 0x17, 0x0f, 0x54, 0xdf, 0xd8,
	0x5b, 0xbd, 0x42, 0x79, 0x00, 0x40, 0x6a, 0x6a, 0x8a, 0x0c, 0x9f, 0xc3, 0x6e, 0xe4, 0xc5, 0xbe,
	0x0a, 0x48, 0x59, 0x90, 0x20, 0xf7, 0x80, 0x49, 0x6a, 0xcd, 0x06, 0xc3, 0x1e, 0x57, 0x07, 0x24,
	0xdc, 0x99, 0x0d, 0xca, 0x31, 0x88, 0x42, 0xe7, 0x18, 0x8a, 0xc8, 0x8b, 0x83, 0xeb, 0x8e, 0x62,
	0x76, 0xb1, 0x0d, 0xc3, 0x47, 0xb3, 0x76, 0x58, 0xa7, 0x44, 0x67, 0x6f, 0x5d, 0x18, 0x7d, 0xb9,
	0xb1, 0x55, 0x59, 0x58, 0x94, 0x12, 0xc4, 0xb2, 0xcc, 0x5a, 0x2f, 0xbe, 0x62, 0x2c, 0x47, 0xd0,
	0xcb, 0xed, 0x8a, 0x2d, 0x04, 0x8a, 0xa0, 0x3c, 0x02, 0x91, 0x69, 0xa7, 0x79, 0xef, 0x70, 0xbe,
	0xdf, 0xa6, 0x4c, 0xbe, 0xff, 0x2c, 0xb9, 0xd2, 0x4e, 0x2b, 0xee, 0x9c, 0xbe, 0x74, 0x41, 0x10,
	0xfd, 0x9f, 0xbc, 0x9f, 0xb3, 0xcb, 0xb2, 0x29, 0x1c, 0xa7, 0xfe, 0x98, 0xbd, 0x24, 0x41, 0x8e,
	0xc1, 0x77, 0xa5, 0xd3, 0xeb, 0xd0, 0xe7, 0x4a, 0x4b, 0xe4, 0x09, 0xf8, 0xc6, 0x61, 0x6e, 0xc3,
	0x7e, 0xd4, 0x8b, 0x87, 0xf3, 0xc3, 0xbf, 0x52, 0x24, 0x0b, 0x87, 0xb9, 0x6a, 0xfb, 0xa7, 0x67,
	0x20, 0x88, 0xd2, 0x5d, 0x1a, 0x93, 0x71, 0x8c, 0x40, 0x11, 0xa4, 0xeb, 0xf1, 0xdd, 0xdb, 0x53,
	0x31, 0xa6, 0x2e, 0x0a, 0xdb, 0x5a, 0x26, 0x38, 0x3f, 0x07, 0x41, 0x4b, 0xe4, 0x29, 0x08, 0x5a,
	0x24, 0x77, 0x7f, 0x6c, 0xe6, 0xa7, 0x31, 0x9d, 0xfc, 0xe2, 0x68, 0xd6, 0x79, 0xe8, 0x73, 0xe5,
	0xf8, 0x3d, 0x00, 0x00, 0xff, 0xff, 0x09, 0xbb, 0x03, 0x5e, 0x65, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	// 用户列表
	List(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) List(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, "/proto.User/CoinMarket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	// 用户列表
	List(context.Context, *UserListRequest) (*UserListResponse, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.User/CoinMarket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).List(ctx, req.(*UserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CoinMarket",
			Handler:    _User_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
