// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 打招呼
type HelloRequest struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type HelloResponse struct {
	Code                 int32               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string              `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *HelloResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HelloResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *HelloResponse) GetData() *HelloResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type HelloResponse_Data struct {
	Replay               string   `protobuf:"bytes,1,opt,name=replay,proto3" json:"replay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse_Data) Reset()         { *m = HelloResponse_Data{} }
func (m *HelloResponse_Data) String() string { return proto.CompactTextString(m) }
func (*HelloResponse_Data) ProtoMessage()    {}
func (*HelloResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1, 0}
}

func (m *HelloResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse_Data.Unmarshal(m, b)
}
func (m *HelloResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse_Data.Marshal(b, m, deterministic)
}
func (m *HelloResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse_Data.Merge(m, src)
}
func (m *HelloResponse_Data) XXX_Size() int {
	return xxx_messageInfo_HelloResponse_Data.Size(m)
}
func (m *HelloResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse_Data proto.InternalMessageInfo

func (m *HelloResponse_Data) GetReplay() string {
	if m != nil {
		return m.Replay
	}
	return ""
}

// 拜拜
type ByeRequest struct {
	Bye                  string   `protobuf:"bytes,1,opt,name=bye,proto3" json:"bye,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByeRequest) Reset()         { *m = ByeRequest{} }
func (m *ByeRequest) String() string { return proto.CompactTextString(m) }
func (*ByeRequest) ProtoMessage()    {}
func (*ByeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{2}
}

func (m *ByeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByeRequest.Unmarshal(m, b)
}
func (m *ByeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByeRequest.Marshal(b, m, deterministic)
}
func (m *ByeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByeRequest.Merge(m, src)
}
func (m *ByeRequest) XXX_Size() int {
	return xxx_messageInfo_ByeRequest.Size(m)
}
func (m *ByeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ByeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ByeRequest proto.InternalMessageInfo

func (m *ByeRequest) GetBye() string {
	if m != nil {
		return m.Bye
	}
	return ""
}

type ByeResponse struct {
	Code                 int32             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string            `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *ByeResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ByeResponse) Reset()         { *m = ByeResponse{} }
func (m *ByeResponse) String() string { return proto.CompactTextString(m) }
func (*ByeResponse) ProtoMessage()    {}
func (*ByeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{3}
}

func (m *ByeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByeResponse.Unmarshal(m, b)
}
func (m *ByeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByeResponse.Marshal(b, m, deterministic)
}
func (m *ByeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByeResponse.Merge(m, src)
}
func (m *ByeResponse) XXX_Size() int {
	return xxx_messageInfo_ByeResponse.Size(m)
}
func (m *ByeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ByeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ByeResponse proto.InternalMessageInfo

func (m *ByeResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ByeResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ByeResponse) GetData() *ByeResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type ByeResponse_Data struct {
	Replay               string   `protobuf:"bytes,1,opt,name=replay,proto3" json:"replay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByeResponse_Data) Reset()         { *m = ByeResponse_Data{} }
func (m *ByeResponse_Data) String() string { return proto.CompactTextString(m) }
func (*ByeResponse_Data) ProtoMessage()    {}
func (*ByeResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{3, 0}
}

func (m *ByeResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByeResponse_Data.Unmarshal(m, b)
}
func (m *ByeResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByeResponse_Data.Marshal(b, m, deterministic)
}
func (m *ByeResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByeResponse_Data.Merge(m, src)
}
func (m *ByeResponse_Data) XXX_Size() int {
	return xxx_messageInfo_ByeResponse_Data.Size(m)
}
func (m *ByeResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_ByeResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_ByeResponse_Data proto.InternalMessageInfo

func (m *ByeResponse_Data) GetReplay() string {
	if m != nil {
		return m.Replay
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "proto.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "proto.HelloResponse")
	proto.RegisterType((*HelloResponse_Data)(nil), "proto.HelloResponse.Data")
	proto.RegisterType((*ByeRequest)(nil), "proto.ByeRequest")
	proto.RegisterType((*ByeResponse)(nil), "proto.ByeResponse")
	proto.RegisterType((*ByeResponse_Data)(nil), "proto.ByeResponse.Data")
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_61ef911816e0a8ce) }

var fileDescriptor_61ef911816e0a8ce = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0x87, 0x6b, 0xf2, 0x47, 0xe5, 0x02, 0x52, 0x39, 0x10, 0x84, 0x0c, 0x55, 0xe5, 0xa9, 0x02,
	0x11, 0x89, 0x32, 0xb0, 0x57, 0x0c, 0xcc, 0xe9, 0x13, 0xb8, 0xf4, 0x14, 0x90, 0x42, 0x1d, 0x62,
	0x33, 0x78, 0x63, 0xe0, 0xc1, 0x91, 0x2f, 0x06, 0x35, 0xa2, 0x4b, 0x27, 0xff, 0xee, 0xf4, 0xdd,
	0xe9, 0x3b, 0x43, 0xf6, 0x4a, 0x4d, 0xa3, 0xcb, 0xb6, 0xd3, 0x56, 0x63, 0xc2, 0x8f, 0xbc, 0x81,
	0x93, 0x67, 0xdf, 0xad, 0xe8, 0xe3, 0x93, 0x8c, 0xc5, 0x02, 0xc6, 0x75, 0x47, 0x64, 0xdf, 0xb6,
	0x75, 0x2e, 0x66, 0x62, 0x7e, 0x5c, 0xfd, 0xd5, 0xf2, 0x5b, 0xc0, 0x69, 0x80, 0x4d, 0xab, 0xb7,
	0x86, 0x10, 0x21, 0x7e, 0xd1, 0x1b, 0x62, 0x32, 0xa9, 0x38, 0xe3, 0x04, 0xa2, 0x77, 0x53, 0xe7,
	0x47, 0x3c, 0xec, 0x23, 0xde, 0x41, 0xbc, 0x51, 0x56, 0xe5, 0xd1, 0x4c, 0xcc, 0xb3, 0xc5, 0x75,
	0x2f, 0x50, 0x0e, 0x36, 0x95, 0x4f, 0xca, 0xaa, 0x8a, 0xb1, 0x62, 0x0a, 0xb1, 0xaf, 0xf0, 0x12,
	0xd2, 0x8e, 0xda, 0x46, 0xb9, 0x20, 0x12, 0x2a, 0x39, 0x05, 0x58, 0x3a, 0xfa, 0x15, 0x9e, 0x40,
	0xb4, 0x76, 0x14, 0x10, 0x1f, 0xe5, 0x97, 0x80, 0x8c, 0x81, 0x83, 0x24, 0x6f, 0x07, 0x92, 0x57,
	0x41, 0x72, 0x67, 0xcf, 0x01, 0x8a, 0x0b, 0x03, 0x09, 0x9f, 0x87, 0x8f, 0x30, 0x5e, 0x29, 0xd7,
	0xe7, 0xf3, 0xe1, 0xe1, 0xac, 0x5f, 0x5c, 0xec, 0xfb, 0x0d, 0x39, 0xc2, 0x7b, 0x48, 0x57, 0xca,
	0x2d, 0x1d, 0xe1, 0xd9, 0xae, 0x4a, 0x3f, 0x84, 0xff, 0xed, 0xe4, 0x68, 0x9d, 0x72, 0xf3, 0xe1,
	0x27, 0x00, 0x00, 0xff, 0xff, 0x24, 0x40, 0x67, 0x6e, 0xe7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloClient interface {
	// 打招呼
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	// 拜拜
	SayBye(ctx context.Context, in *ByeRequest, opts ...grpc.CallOption) (*ByeResponse, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/proto.Hello/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloClient) SayBye(ctx context.Context, in *ByeRequest, opts ...grpc.CallOption) (*ByeResponse, error) {
	out := new(ByeResponse)
	err := c.cc.Invoke(ctx, "/proto.Hello/SayBye", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServer is the server API for Hello service.
type HelloServer interface {
	// 打招呼
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	// 拜拜
	SayBye(context.Context, *ByeRequest) (*ByeResponse, error)
}

// UnimplementedHelloServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServer struct {
}

func (*UnimplementedHelloServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedHelloServer) SayBye(ctx context.Context, req *ByeRequest) (*ByeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayBye not implemented")
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hello/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hello_SayBye_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).SayBye(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hello/SayBye",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).SayBye(ctx, req.(*ByeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Hello_SayHello_Handler,
		},
		{
			MethodName: "SayBye",
			Handler:    _Hello_SayBye_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
